"""Public db API.

This package intentionally exposes only the interfaces currently used by other
modules. Internal helpers and connection primitives stay in their dedicated
modules and are not exported here.
"""

from cdnmanager.db.credentials import (
    delete_credential,
    delete_dns_credential,
    delete_root_domain,
    delete_storage_credential,
    delete_storage_target,
    get_dns_credential,
    get_root_domain,
    get_storage_credential,
    get_storage_target,
    load_credentials,
    load_dns_credentials,
    load_root_domains,
    load_storage_credentials,
    load_storage_targets,
    upsert_credential,
    upsert_dns_credential,
    upsert_root_domain,
    upsert_storage_credential,
    upsert_storage_target,
)
from cdnmanager.db.domains import (
    acquire_domain_refresh,
    delete_domain_record,
    get_domain,
    get_url_by_id,
    insert_url,
    insert_url_record,
    load_domains,
    load_refreshing_domains,
    load_refreshing_urls,
    load_url_records,
    load_urls,
    prune_urls_for_domain,
    try_acquire_polling_lease,
    update_domain_fields,
    update_url_by_id,
    upsert_domain,
)
from cdnmanager.db.models import ensure_database
from cdnmanager.db.projects import (
    _normalize_allowed_users,
    delete_environment,
    delete_project,
    filter_projects_tree,
    generate_api_key,
    get_environment,
    get_environment_by_name,
    get_project,
    get_project_by_name,
    get_user_project_ids,
    list_storage_targets_for_environment,
    load_environments,
    load_projects,
    load_projects_tree,
    remove_user_from_projects,
    sync_domain_tags_from_ids,
    sync_user_project_authorization,
    upsert_environment,
    upsert_project,
    user_can_access_project,
)
from cdnmanager.db.uploads import (
    cleanup_finished_upload_job,
    count_upload_files,
    count_upload_jobs,
    delete_upload_job_cascade,
    get_upload_file,
    get_upload_job,
    increment_upload_job_totals,
    insert_upload_files,
    insert_upload_job,
    insert_upload_parts,
    list_failed_upload_files,
    list_stale_uploading_files,
    list_upload_files,
    list_upload_jobs,
    list_upload_parts,
    recalculate_upload_job_stats,
    update_upload_file,
    update_upload_job,
    update_upload_part,
)
from cdnmanager.db.users import (
    delete_user,
    get_user,
    load_users,
    remove_user_from_domains,
    upsert_user,
)

__all__ = [
    'ensure_database',
    'load_users', 'get_user', 'upsert_user', 'delete_user', 'remove_user_from_domains',
    'load_credentials', 'upsert_credential', 'delete_credential',
    'load_dns_credentials', 'get_dns_credential', 'upsert_dns_credential', 'delete_dns_credential',
    'load_root_domains', 'get_root_domain', 'upsert_root_domain', 'delete_root_domain',
    'load_storage_credentials', 'get_storage_credential', 'upsert_storage_credential', 'delete_storage_credential',
    'load_storage_targets', 'get_storage_target', 'upsert_storage_target', 'delete_storage_target',
    'load_domains', 'get_domain', 'upsert_domain', 'delete_domain_record', 'update_domain_fields',
    'acquire_domain_refresh', 'insert_url_record', 'insert_url', 'update_url_by_id', 'get_url_by_id',
    'load_url_records', 'load_urls', 'prune_urls_for_domain', 'load_refreshing_domains',
    'load_refreshing_urls', 'try_acquire_polling_lease',
    'generate_api_key', '_normalize_allowed_users', 'user_can_access_project',
    'load_projects', 'get_project', 'get_project_by_name', 'upsert_project', 'delete_project',
    'load_environments', 'get_environment', 'get_environment_by_name', 'upsert_environment', 'delete_environment',
    'list_storage_targets_for_environment', 'load_projects_tree', 'filter_projects_tree', 'get_user_project_ids',
    'sync_user_project_authorization', 'remove_user_from_projects', 'sync_domain_tags_from_ids',
    'list_upload_jobs', 'list_upload_files', 'get_upload_job', 'get_upload_file', 'insert_upload_job',
    'insert_upload_files', 'update_upload_file', 'update_upload_job', 'increment_upload_job_totals',
    'count_upload_jobs', 'count_upload_files', 'list_failed_upload_files', 'list_stale_uploading_files',
    'insert_upload_parts', 'list_upload_parts', 'update_upload_part', 'recalculate_upload_job_stats',
    'delete_upload_job_cascade', 'cleanup_finished_upload_job',
]
